version: '3.9'

services:
  vm1-headnode:
    container_name: vm1-headnode
    image: docker_headnode:1.6
    expose:
      - "9870"
      - "8088"
    ports:
      - "9870:9870"
      - "8088:8088"
    networks:
      - net-for-hadoop
    volumes:
      - data-volume-headnode:/opt

  vm2-worker:
    container_name: vm2-worker
    image: docker_worker:1.6
    networks:
      - net-for-hadoop
    volumes:
      - data-volume-worker:/opt

networks:
  net-for-hadoop:
    driver: bridge
    name: net-for-hadoop

volumes:
  data-volume-headnode:
  data-volume-worker:
