---
- name: Download repo
  ansible.builtin.get_url:
    url: http://repo.mysql.com/mysql-community-release-el6-5.noarch.rpm
    dest: /opt/mysql-community-release-el6-5.noarch.rpm

- name: Install package mysql
  ansible.builtin.yum:
    name: /opt/mysql-community-release-el6-5.noarch.rpm
    state: present

- name: Install mysql
  ansible.builtin.yum:
    update_cache: yes
    name:
      - mysql-server
      - MySQL-python
    state: latest

- name: start up the mysqld service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Create database
  community.mysql.mysql_db:
    name: "{{ mysql_name_DB }}"
    state: present

- name: Create database user with name 'bob' and password '12345' with all database privileges
  community.mysql.mysql_user:
    name: "{{ mysql_name_user }}"
    password: "{{ mysql_password_user }}"
    priv: '*.*:ALL'
    state: present
